spring:
  application:
    name: security-jmv

  datasource:
    url: jdbc:h2:mem:jmv_security_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

jwt:
  secret-key: ${SECRET_KEY}
  expiration-time: ${EXPIRATION:1800000} # 30 minutos em milissegundos
  refresh-expiration-time: ${REFRESH-TOKEN-EXPIRATION:604800000}  # 7 dias em milissegundos
